# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f9f3bb5dd64751f8a5e2cd5dce899af97ba47138627aad3bc996928d4ab8cfac02f02574f95a6e0169a26b89a387f66dd31a1650df7f46ee7fec86050549a6e

test:
  secret_key_base: 66902bbda033524b0d712e2124cfffb1db22310638d85272ee72c53059877f659808475ab54ebe28b2feb2a30eebbbebd263a4e436e2d752d020f3e045d6e81e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
